spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#    url: ${POSTGRES_DB:jdbc:postgresql://localhost:5432/heroku_test}
#    username: ${POSTGRES_USER:postgres}
#    password: ${POSTGRES_DB:root}
#server:
#  port: ${PORT:8080}